/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v14.0
processor: LPC804
package_id: LPC804M101JDH24
mcu_data: ksdk2_0
processor_version: 14.0.0
board: LPCXpresso804
pin_labels:
- {pin_num: '10', pin_signal: PIO0_11/ADC_6/WKTCLKIN, label: 'CN6[10]/CN8[3]/D4/PIO0_11/M_PIO0_11', identifier: LED_BLUE;Dig1}
- {pin_num: '5', pin_signal: PIO0_12, label: 'S2/CN8[6]/CN6[5]/D3/M_PIO0_12/PIO0_12', identifier: LED_GREEN;S2;Dig2}
- {pin_num: '4', pin_signal: PIO0_13/ADC_10, label: 'S1/CN8[4]/CN6[4]/D2/M_PIO0_13/PIO0_13', identifier: LED_RED;S1;Dig3}
- {pin_num: '22', pin_signal: PIO0_0/ACMP_I1, label: 'CN7[3]/CN8[8]/JP2/PIO0_0', identifier: DEBUG_UART_RX;segG}
- {pin_num: '7', pin_signal: PIO0_4/ADC_11, label: 'CN6[7]/CN8[7]/CN5[5]/JP24/PIO0_4', identifier: DEBUG_UART_TX;segB}
- {pin_num: '23', pin_signal: PIO0_14/ACMP_I3/ADC_2, label: 'CN7[2]/CN3[1]/JP4/PIO0_14', identifier: I2C_SCL;Dig4}
- {pin_num: '20', pin_signal: PIO0_7/ADC_1/ACMPVREF, label: 'CN7[5]/CN3[2]/JP23/CN5[4]/PIO0_7', identifier: I2C_SDA;segC}
- {pin_num: '2', pin_signal: PIO0_16/ACMP_I4/ADC_3, label: 'CN6[2]/CN5[2]/U4[1]/PIO0_16', identifier: segE}
- {pin_num: '3', pin_signal: PIO0_17/ADC_9, label: 'CN6[3]/CN5[3]/PIO0_17', identifier: segD}
- {pin_num: '11', pin_signal: PIO0_10/ADC_7, label: 'CN6[11]/VR1/CN5[1]/PIO0_10', identifier: segF}
- {pin_num: '15', pin_signal: PIO0_1/ADC_0/ACMP_I2/CLKIN, label: 'CN7[10]/CN3[5]/CN5[6]/U4[6]/PIO0_1', identifier: segA}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '15', peripheral: GPIO, signal: 'PIO0, 1', pin_signal: PIO0_1/ADC_0/ACMP_I2/CLKIN, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '7', peripheral: GPIO, signal: 'PIO0, 4', pin_signal: PIO0_4/ADC_11, identifier: segB, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '20', peripheral: GPIO, signal: 'PIO0, 7', pin_signal: PIO0_7/ADC_1/ACMPVREF, identifier: segC, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '3', peripheral: GPIO, signal: 'PIO0, 17', pin_signal: PIO0_17/ADC_9, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '2', peripheral: GPIO, signal: 'PIO0, 16', pin_signal: PIO0_16/ACMP_I4/ADC_3, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '11', peripheral: GPIO, signal: 'PIO0, 10', pin_signal: PIO0_10/ADC_7, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '22', peripheral: GPIO, signal: 'PIO0, 0', pin_signal: PIO0_0/ACMP_I1, identifier: segG, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '10', peripheral: GPIO, signal: 'PIO0, 11', pin_signal: PIO0_11/ADC_6/WKTCLKIN, identifier: Dig1, direction: OUTPUT}
  - {pin_num: '5', peripheral: GPIO, signal: 'PIO0, 12', pin_signal: PIO0_12, identifier: Dig2, direction: OUTPUT}
  - {pin_num: '4', peripheral: GPIO, signal: 'PIO0, 13', pin_signal: PIO0_13/ADC_10, identifier: Dig3, direction: OUTPUT}
  - {pin_num: '23', peripheral: GPIO, signal: 'PIO0, 14', pin_signal: PIO0_14/ACMP_I3/ADC_2, identifier: Dig4, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitPins(void)
{
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t segG_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_0 (pin 22)  */
    GPIO_PinInit(BOARD_segG_GPIO, BOARD_segG_PORT, BOARD_segG_PIN, &segG_config);

    gpio_pin_config_t segA_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_1 (pin 15)  */
    GPIO_PinInit(BOARD_segA_GPIO, BOARD_segA_PORT, BOARD_segA_PIN, &segA_config);

    gpio_pin_config_t segB_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_4 (pin 7)  */
    GPIO_PinInit(BOARD_segB_GPIO, BOARD_segB_PORT, BOARD_segB_PIN, &segB_config);

    gpio_pin_config_t segC_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_7 (pin 20)  */
    GPIO_PinInit(BOARD_segC_GPIO, BOARD_segC_PORT, BOARD_segC_PIN, &segC_config);

    gpio_pin_config_t segF_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_10 (pin 11)  */
    GPIO_PinInit(BOARD_segF_GPIO, BOARD_segF_PORT, BOARD_segF_PIN, &segF_config);

    gpio_pin_config_t Dig1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_11 (pin 10)  */
    GPIO_PinInit(BOARD_Dig1_GPIO, BOARD_Dig1_PORT, BOARD_Dig1_PIN, &Dig1_config);

    gpio_pin_config_t Dig2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_12 (pin 5)  */
    GPIO_PinInit(BOARD_Dig2_GPIO, BOARD_Dig2_PORT, BOARD_Dig2_PIN, &Dig2_config);

    gpio_pin_config_t Dig3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_13 (pin 4)  */
    GPIO_PinInit(BOARD_Dig3_GPIO, BOARD_Dig3_PORT, BOARD_Dig3_PIN, &Dig3_config);

    gpio_pin_config_t gpio0_pin0_14 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_14 (pin )  */
    GPIO_PinInit(GPIO, 0U, 14U, &gpio0_pin0_14);

    gpio_pin_config_t segE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_16 (pin 2)  */
    GPIO_PinInit(BOARD_segE_GPIO, BOARD_segE_PORT, BOARD_segE_PIN, &segE_config);

    gpio_pin_config_t segD_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_17 (pin 3)  */
    GPIO_PinInit(BOARD_segD_GPIO, BOARD_segD_PORT, BOARD_segD_PIN, &segD_config);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
